var mongoose = require('mongoose');

var Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;
var bloodDonationSchema = new Schema({
    donor_id: {type: ObjectId, required: false}, 
    donor_name: {type: String, required: false},
    appointment_date: {type: Date, required: true},
    appointment_time: {type: String, required: true},
    date_completed: {type: Date, required: false},
    status: {type: String, default: 'initial'},
    chapter: {type: mongoose.Schema.Types.ObjectId, ref: 'chapter', required: true},
    blood_group: {type: String, required: false},
    bags_donated: {type: Number, default: 0},
    blood_product_donated: {type: String, required: false},
    donation_type: {type: String, required: false}, //false muna
    patient_directed_name: {type: String, required: false}, //false muna
},{collection: 'donation_appointment'});

/*
donor_id: {type: ObjectId, required: false}, 
   
    appointment_date: {type: Date, required: true},
    appointment_time: {type: String, required: true},
    date_completed: {type: Date, required: false},
    blood_group: {type: String, required: false},
    blood_product_donated: {type: String, required: false},
    lastname: { type: String, required: false},
    firstname: { type: String, required: false},
    middlename: { type: String, required: false},
    address: { type: String, required: false},
     body_wt: { type: String, required: false },
    sp_gr: { type: String, required: false },
    hgb: { type: String, required: false },
    hct: { type: String, required: false },
    rbc: { type: String, required: false },
    wbc: { type: String, required: false },
    plt_count: { type: String, required: false },
    donation_type: { type: String, required: false },
    patient_name: { type: String, required: false },
    patient_hospital: { type: String, required: false },
    patient_bloodtype: { type: String, required: false },
    patient_wb: { type: String, required: false },
    patient_no_units: { type: String, required: false },
    interviewer: { type: String, required: false},
    bloodbag_used: { type: String, required: false},
    amount_of_blood: { type: String, required: false},
    successful: { type: String, required: false},
    donor_reaction: { type: String, required: false},
    management_done: { type: String, required: false},
    serial_code: { type: String, required: false},
    start_time: { type: String, required: false },
    end_time: { type: String, required: false },
    date: { type: String, required: false},
    volume: { type: String, required: false },
    branch: { type: String, required: false,default:'none' },
    branch_id: { type: String, required: false,default:'none' },
    deferral_type: { type: String, required: false },
    status: { type: String, required: false},
    contact: { type: Number, required: false},
    birthday: { type: String, required: false},
    deferral_date: { type: String, required: false },
    blood_pressure: { type: String,required: false},
    pulse_rate: { type: String,required: false},
    body_temp: { type: String,required: false},
    gen_appearance: { type: String,required: false},
    skin: { type: String,required: false},
    HEENT: { type: String,required: false},
    heart_lungs: { type: String,required: false},
    remarks: { type: String,required: false},
    reason: { type: String,required: false},
    bag_used: { type: String,required: false},
*/

module.exports = mongoose.model('Blood_Donations', bloodDonationSchema);